---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: {{ include "homeassistant.ns" . }}
  labels:
    app: homeassistant
    component: homeassistant
spec:
  type: {{ .Values.homeassistant.service.type }}
  selector:
    app: homeassistant
    component: homeassistant
  ports:
    - name: http
      port: {{ .Values.homeassistant.service.port }}
      targetPort: 8123
      protocol: TCP
      {{- if eq .Values.homeassistant.service.type "NodePort" }}
      nodePort: {{ .Values.homeassistant.service.nodePort }}
      {{- end }}
