---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    app: homeassistant
    component: postgres
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  POSTGRES_DB: {{ .Values.secrets.postgresDb | quote }}
  # Connection URL for Home Assistant recorder configuration
  # postgresql://homeassistant:changeme@postgres.homeassistant.svc.cluster.local:5432/homeassistant?client_encoding=utf8
